# Site settings
title: "Niels Lensink"
description: "Software Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_logo: "true"
resume_name: null
resume_title: "Niels Lensink - Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "nielslensink@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: ""
resume_contact_address: ""

resume_header_contact_info: "nielslensink@gmail.com"
display_header_contact_info: "false"

resume_header_intro: |
  Passionate engineer with 18+ years of experience in backend development, DevOps, infrastructure, and machine learning. 
  Known for delivering scalable, pragmatic solutions across cloud-native platforms, high-performance APIs, and real-time data systems. 
  Experienced in leading cross-functional teams and driving technical architecture in complex environments.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work: "no"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: false
resume_section_skills: false
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
resume_section_interests: false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/snelis"
  resume_twitter_url: null
  resume_dribbble_url: null
  resume_facebook_url: null
  resume_linkedin_url: "https://www.linkedin.com/in/nielslensink/"
  resume_instagram_url: null
  resume_website_url: "https://nielslensink.com"
  resume_medium_url: null
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
